.TH BASL 1 "December 2015" "1.0"
.SH NAME
BASL \- Bourne Again Social Life 

.SH SYNOPSIS
basl <OPTION>

.SH DESCRIPTION
BASL is a program which will send "happy birthday" and "happy new year" SMS messages to your relatives.

.SH OPTIONS
.IP \fB-b\fP
Sends "Happy Birthday" messages to your contacts whose birthday date matches the current date. 

.IP \fB-n\fP
Sends "Happy New Year" messages to your contacts whose newyear value corresponds to "Y".

.SH SEE ALSO
asterisk(8)

.SH BUGS
Please report bugs on
.I https://github.com/Encrypt/basl/issues

.SH AUTHOR
Yann Privé <encrypt@encrypt-tips.tk>
